/* global YT, SC, RADIO_DATA */
const state={day:'2026-10-02',artistIndex:0,phase:'idle',songIndex:0,playing:false,player:null,soundcloud:null,voice:null};
const $=s=>document.querySelector(s);
const dayLabels={'2026-10-02':'DAY 1 · 10.02','2026-10-03':'DAY 2 · 10.03','2026-10-04':'DAY 3 · 10.04'};
function artists(){return RADIO_DATA.days.find(d=>d.date===state.day)?.artists||[]}
function currentArtist(){return artists()[state.artistIndex]}
function escapeHtml(v=''){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderTabs(){const root=$('#dayTabs');root.innerHTML=RADIO_DATA.days.map(d=>`<button class="day-tab ${d.date===state.day?'active':''}" data-day="${d.date}">${dayLabels[d.date]} · ${d.artists.length}팀</button>`).join('');root.querySelectorAll('button').forEach(b=>b.onclick=()=>selectDay(b.dataset.day))}
function renderGrid(){const list=artists();$('#artistCount').textContent=`${list.length} ARTISTS`;$('#artistGrid').innerHTML=list.map((a,i)=>`<article class="artist-card ${i===state.artistIndex?'active':''}" data-index="${i}"><span class="artist-card__index">${String(i+1).padStart(2,'0')} / ${dayLabels[state.day]}</span><h3>${escapeHtml(a.artist)}</h3><p>${escapeHtml(a.intro||'아티스트 소개를 준비하고 있습니다.')}</p><div class="artist-card__songs">${(a.songs||[]).map(s=>escapeHtml(s.title)).join(' · ')||'대표곡 준비 중'}</div></article>`).join('');document.querySelectorAll('.artist-card').forEach(c=>c.onclick=()=>jumpToArtist(Number(c.dataset.index)))}
function selectDay(day){stopAll();state.day=day;state.artistIndex=0;state.songIndex=0;state.phase='idle';render();updateNow('선택됨','라디오 시작을 누르세요.')}
function jumpToArtist(index){stopAll();state.artistIndex=index;state.songIndex=0;state.phase='intro';render();startCurrent()}
function render(){renderTabs();renderGrid();const a=currentArtist();$('#nowDay').textContent=dayLabels[state.day];$('#nowArtist').textContent=a?.artist||'라인업 준비 중';$('#nowTitle').textContent='재생 대기 중';$('#nowStory').textContent=a?.anecdote||a?.intro||'소개를 준비하고 있습니다.';setProgress()}
function setStatus(text){$('#statusText').textContent=text}
function updateNow(title,story,link){const a=currentArtist();$('#nowArtist').textContent=a?.artist||'';$('#nowTitle').textContent=title;$('#nowStory').textContent=story||a?.anecdote||a?.intro||'';$('#sourceLink').href=link||a?.sources?.[0]||'https://busanrockfestival.com/lineup/';$('#sourceLink').textContent=link?'공식 영상 열기 ↗':'정보 출처 열기 ↗';document.querySelectorAll('.artist-card').forEach((c,i)=>c.classList.toggle('active',i===state.artistIndex));setProgress()}
function setProgress(){const list=artists();const a=currentArtist();const total=Math.max(1,list.reduce((n,x)=>n+1+(x.songs?.length||0),0));let done=0;for(let i=0;i<state.artistIndex;i++)done+=1+(list[i].songs?.length||0);done+=state.phase==='song'?1+state.songIndex:state.phase==='done'?1+(a?.songs?.length||0):0;$('#progressBar').style.width=`${Math.min(100,done/total*100)}%`}
function chooseVoice(){const voices=speechSynthesis.getVoices();state.voice=voices.find(v=>v.lang==='ko-KR'&&/female|sunhi|yuna|sora|kyuri/i.test(v.name))||voices.find(v=>v.lang==='ko-KR')||null}
speechSynthesis.onvoiceschanged=chooseVoice;chooseVoice();
function speak(text,onend){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ko-KR';u.rate=.98;u.pitch=1;u.voice=state.voice;u.onend=onend;u.onerror=onend;speechSynthesis.speak(u)}
function narrationText(a){const songs=(a.songs||[]).map((s,i)=>`${i+1}번, ${s.title}. ${s.why||''}`).join(' ');return `${a.artist}. ${a.intro||''} 꼭 들어볼 세 곡은 ${songs} ${a.anecdote||''}`}
function startRadio(){if(!artists().length)return;state.playing=true;$('#playButton').textContent='Ⅱ 일시정지';startCurrent()}
function startCurrent(){const a=currentArtist();if(!a)return finishDay();state.phase='intro';state.songIndex=0;renderGrid();updateNow('아티스트 소개',a.intro||'소개를 준비하고 있습니다.');setStatus(`${a.artist} 소개 재생 중`);if($('#narrationToggle').checked){speak(narrationText(a),()=>playSongOrAdvance())}else playSongOrAdvance()}
function playSongOrAdvance(){const a=currentArtist();if(!$('#songsToggle').checked||!a.songs?.length)return advanceArtist();if(state.songIndex>=a.songs.length)return advanceArtist();const song=a.songs[state.songIndex];state.phase='song';updateNow(`${state.songIndex+1}. ${song.title}`,song.why||a.anecdote,song.url);setStatus(`${a.artist} — ${song.title}`);const id=song.youtubeId||extractYouTubeId(song.url);if(id)return playYouTube(id);if(/soundcloud\.com/.test(song.url||''))return playSoundCloud(song.url);setStatus('직접 재생할 수 없는 곡이라 다음 곡으로 이동합니다.');setTimeout(()=>{state.songIndex++;playSongOrAdvance()},900)}
function extractYouTubeId(url=''){const m=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{11})/);return m?.[1]||''}
function playYouTube(id){state.soundcloud?.pause();$('#soundcloudPlayer').hidden=true;showPlayer();if(state.player&&state.player.loadVideoById)state.player.loadVideoById(id);else state.pendingVideo=id}
function playSoundCloud(url){state.player?.pauseVideo();showPlayer();const frame=$('#soundcloudPlayer');frame.hidden=false;frame.src=`https://w.soundcloud.com/player/?url=${encodeURIComponent(url)}&auto_play=true&visual=true`;state.soundcloud=SC.Widget(frame);state.soundcloud.bind(SC.Widget.Events.READY,()=>state.soundcloud.play());state.soundcloud.bind(SC.Widget.Events.FINISH,()=>{state.songIndex++;playSongOrAdvance()})}
function advanceArtist(){state.artistIndex++;state.songIndex=0;if(state.artistIndex>=artists().length)return finishDay();startCurrent()}
function next(){speechSynthesis.cancel();if(state.phase==='song'){state.songIndex++;playSongOrAdvance()}else advanceArtist()}
function prev(){speechSynthesis.cancel();if(state.phase==='song'&&state.songIndex>0){state.songIndex--;playSongOrAdvance()}else{state.artistIndex=Math.max(0,state.artistIndex-1);startCurrent()}}
function pauseResume(){if(!state.playing){state.playing=true;$('#playButton').textContent='Ⅱ 일시정지';if(state.phase==='song'){state.player?.playVideo();state.soundcloud?.play()}else startCurrent();return}state.playing=false;$('#playButton').textContent='▶ 계속 듣기';speechSynthesis.pause();state.player?.pauseVideo();state.soundcloud?.pause();setStatus('일시정지')}
function finishDay(){state.phase='done';state.playing=false;$('#playButton').textContent='↻ 다시 듣기';updateNow('오늘의 라디오가 끝났습니다.','다른 날짜를 선택하거나 처음부터 다시 들을 수 있습니다.');setStatus(`${dayLabels[state.day]} 재생 완료`)}
function stopAll(){speechSynthesis.cancel();state.player?.stopVideo();state.soundcloud?.pause();state.playing=false;$('#playButton').textContent='▶ 라디오 시작'}
function showPlayer(){$('#videoPlaceholder').style.display='none'}
window.onYouTubeIframeAPIReady=()=>{state.player=new YT.Player('youtubePlayer',{height:'390',width:'640',videoId:'',playerVars:{autoplay:1,playsinline:1,rel:0,modestbranding:1,origin:location.origin},events:{onReady:()=>{if(state.pendingVideo){state.player.loadVideoById(state.pendingVideo);state.pendingVideo=null}},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED){state.songIndex++;playSongOrAdvance()}},onError:()=>{setStatus('이 영상은 임베드가 제한되어 다음 곡으로 이동합니다.');setTimeout(()=>{state.songIndex++;playSongOrAdvance()},900)}}})};
$('#playButton').onclick=pauseResume;$('#nextButton').onclick=next;$('#prevButton').onclick=prev;render();
